/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppointmentResponseDto } from './models/appointment-response-dto';
export type { CreateAppointmentRequestDto } from './models/create-appointment-request-dto';
export type { CreateMedicalServiceRequestDto } from './models/create-medical-service-request-dto';
export type { LocalTime } from './models/local-time';
export type { LoginRequestDto } from './models/login-request-dto';
export type { LoginResponseDto } from './models/login-response-dto';
export type { MedicalService } from './models/medical-service';
export type { MedicalServiceResponseDto } from './models/medical-service-response-dto';
export type { SignupRequestDto } from './models/signup-request-dto';
