/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ServiciosMedicosService } from './services/servicios-medicos.service';
export { AutenticacionService } from './services/autenticacion.service';
export { CitasService } from './services/citas.service';
export { AdminControllerService } from './services/admin-controller.service';
