/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface AppointmentResponseDto {
  date?: string;
  endTime?: LocalTime;
  id?: number;
  serviceId?: number;
  startTime?: LocalTime;
  status?: string;
  userId?: number;
}
