/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMedicalServiceRequestDto {
  durationMinutes?: number;
  name: string;
  price?: number;
}
