/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MedicalServiceResponseDto {
  durationMinutes?: number;
  id?: number;
  name?: string;
}
