/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MedicalService {
  durationMinutes?: number;
  id?: number;
  name?: string;
  price?: number;
}
